# ----------------------------------------------
#            Install all brew packages
# ----------------------------------------------
- name: Run Brew setup script
  tags: brew
  shell: bash "{{ ansible_env.HOME }}/Pets/ansible/scripts/brew-packages.sh"
  register: brew_setup

- name: Output Brew setup results
  debug:
    var: brew_setup.stdout
