# ----------------------------------------------
#            Install local scripts
# ----------------------------------------------
- name: Run update-alacritty-icon script
  tags: local-scripts
  shell: bash "{{ ansible_env.HOME }}/dotfiles/.local/scripts/update-alacritty-icon.sh"
  register: alacritty_icon_script

- name: Output results of update-alacritty-icon script
  debug:
    var: alacritty_icon_script.stdout
