name: Test Ansible Playbook

on:
  push:
    branches: ["main"] # Trigger workflow on push to main
  pull_request:
    branches: ["main"] # Trigger on pull requests to main
  workflow_dispatch:

jobs:
  ansible-test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Homebrew (if required)
        run: |
          if ! command -v brew &>/dev/null; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi

      - name: Install Ansible via Homebrew
        run: |
          brew install ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook ansible/setup_new_machine.yml
